//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("alwatnia.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Company.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University / Institute / School.
        /// </summary>
        public static string AcademicInstatue {
            get {
                return ResourceManager.GetString("AcademicInstatue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and Activities.
        /// </summary>
        public static string ActivitiesEvents {
            get {
                return ResourceManager.GetString("ActivitiesEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity ended.
        /// </summary>
        public static string ActivityEnded {
            get {
                return ResourceManager.GetString("ActivityEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add computer skill.
        /// </summary>
        public static string AddComputerSkill {
            get {
                return ResourceManager.GetString("AddComputerSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add course.
        /// </summary>
        public static string AddCourse {
            get {
                return ResourceManager.GetString("AddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add job.
        /// </summary>
        public static string AddJob {
            get {
                return ResourceManager.GetString("AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add qualifcation.
        /// </summary>
        public static string AddQualification {
            get {
                return ResourceManager.GetString("AddQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Industrial City-Riyadh.
        /// </summary>
        public static string AddressLocation {
            get {
                return ResourceManager.GetString("AddressLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Watania For Industries.
        /// </summary>
        public static string Alwatania {
            get {
                return ResourceManager.GetString("Alwatania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I certify the location of this application that the written statements are correct and any fallacy or omission of the facts in this application is a reason for my work in case of employment. In the event of my appointment I agree to the medical examination and agree to be used in accordance with the Company&apos;s rules, regulations and any amendments thereto..
        /// </summary>
        public static string ApplicationAgreenment {
            get {
                return ResourceManager.GetString("ApplicationAgreenment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic language.
        /// </summary>
        public static string ArabicLanguage {
            get {
                return ResourceManager.GetString("ArabicLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaialable.
        /// </summary>
        public static string Avaialable {
            get {
                return ResourceManager.GetString("Avaialable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chairman.
        /// </summary>
        public static string BC {
            get {
                return ResourceManager.GetString("BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        public static string Beginner {
            get {
                return ResourceManager.GetString("Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We wish you all success in your practical career..
        /// </summary>
        public static string BestWishes {
            get {
                return ResourceManager.GetString("BestWishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chairman.
        /// </summary>
        public static string BoardChairman {
            get {
                return ResourceManager.GetString("BoardChairman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Chairman Word.
        /// </summary>
        public static string BoardChairmanWord {
            get {
                return ResourceManager.GetString("BoardChairmanWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we ask your employer about you ?.
        /// </summary>
        public static string CanContactCompany {
            get {
                return ResourceManager.GetString("CanContactCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career opportunities.
        /// </summary>
        public static string CareerOpportunities {
            get {
                return ResourceManager.GetString("CareerOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did&apos;nt find a job that suits you? Do&apos;nt worry, you can send your resume and it will be saved in the recruitment department CV. You can start and click.
        /// </summary>
        public static string CareerSummary {
            get {
                return ResourceManager.GetString("CareerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO Message.
        /// </summary>
        public static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifications and Accreditations.
        /// </summary>
        public static string CertificationsAndAccreditations {
            get {
                return ResourceManager.GetString("CertificationsAndAccreditations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطئ اثناء تغيير كلمة المرور..
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of birth.
        /// </summary>
        public static string CityOfBirth {
            get {
                return ResourceManager.GetString("CityOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company address and contact information.
        /// </summary>
        public static string CompanyAddressAndDetails {
            get {
                return ResourceManager.GetString("CompanyAddressAndDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name and contact persone.
        /// </summary>
        public static string CompanyNameAndDetails {
            get {
                return ResourceManager.GetString("CompanyNameAndDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer skills.
        /// </summary>
        public static string ComputerSkills {
            get {
                return ResourceManager.GetString("ComputerSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever been convicted of any crime that violates honor or trust?.
        /// </summary>
        public static string Conduct {
            get {
                return ResourceManager.GetString("Conduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact employment department.
        /// </summary>
        public static string ContactEmploymentDepartment {
            get {
                return ResourceManager.GetString("ContactEmploymentDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation.
        /// </summary>
        public static string Conversation {
            get {
                return ResourceManager.GetString("Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Strategy.
        /// </summary>
        public static string CorporateStrategy {
            get {
                return ResourceManager.GetString("CorporateStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown started.
        /// </summary>
        public static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of birth.
        /// </summary>
        public static string CountryOfBirth {
            get {
                return ResourceManager.GetString("CountryOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career opportunities.
        /// </summary>
        public static string Creers {
            get {
                return ResourceManager.GetString("Creers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you currently employed?.
        /// </summary>
        public static string CurrentEmployementStatus {
            get {
                return ResourceManager.GetString("CurrentEmployementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV File.
        /// </summary>
        public static string CVTitle {
            get {
                return ResourceManager.GetString("CVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display more.
        /// </summary>
        public static string DisplayMore {
            get {
                return ResourceManager.GetString("DisplayMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display way.
        /// </summary>
        public static string DisplayWay {
            get {
                return ResourceManager.GetString("DisplayWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorcee.
        /// </summary>
        public static string Divorcee {
            get {
                return ResourceManager.GetString("Divorcee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Docx {
            get {
                return ResourceManager.GetString("Docx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Center.
        /// </summary>
        public static string DownloadCenter {
            get {
                return ResourceManager.GetString("DownloadCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone of the employer.
        /// </summary>
        public static string EmployerTele {
            get {
                return ResourceManager.GetString("EmployerTele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Department.
        /// </summary>
        public static string EmploymentDepartment {
            get {
                return ResourceManager.GetString("EmploymentDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment History.
        /// </summary>
        public static string EmploymentHistory {
            get {
                return ResourceManager.GetString("EmploymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cart is empty.
        /// </summary>
        public static string EmptyCart {
            get {
                return ResourceManager.GetString("EmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English language.
        /// </summary>
        public static string EnglishLangauge {
            get {
                return ResourceManager.GetString("EnglishLangauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work environment.
        /// </summary>
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمتاز الشركة الوطنية للصناعة ببيئة عمل مميزة واهتمام بالكادر البشري والعديد من المميزات التي كان نتيجتها الاستقرار الوظيفي والاداء المميز..
        /// </summary>
        public static string EnvironmentIntro {
            get {
                return ResourceManager.GetString("EnvironmentIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Management.
        /// </summary>
        public static string ExecutiveManagement {
            get {
                return ResourceManager.GetString("ExecutiveManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and Exhibitions.
        /// </summary>
        public static string ExhibitionsConferences {
            get {
                return ResourceManager.GetString("ExhibitionsConferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly salary you expect ?.
        /// </summary>
        public static string ExpectedSalary {
            get {
                return ResourceManager.GetString("ExpectedSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of dependents.
        /// </summary>
        public static string FamilyNo {
            get {
                return ResourceManager.GetString("FamilyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantages.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First academic qualification.
        /// </summary>
        public static string FirstAcademic {
            get {
                return ResourceManager.GetString("FirstAcademic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Instagram.
        /// </summary>
        public static string FollowInsta {
            get {
                return ResourceManager.GetString("FollowInsta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on LinkedIn.
        /// </summary>
        public static string FollowLinkedIn {
            get {
                return ResourceManager.GetString("FollowLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on twitter.
        /// </summary>
        public static string FollowUsOnTwitter {
            get {
                return ResourceManager.GetString("FollowUsOnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Youtube.
        /// </summary>
        public static string FollowYoutube {
            get {
                return ResourceManager.GetString("FollowYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you worked in Wataniya Industries?.
        /// </summary>
        public static string FormerWorker {
            get {
                return ResourceManager.GetString("FormerWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full search.
        /// </summary>
        public static string FullSearch {
            get {
                return ResourceManager.GetString("FullSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Year.
        /// </summary>
        public static string GraduationYear {
            get {
                return ResourceManager.GetString("GraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recruitment department is always available for any inquiry. Please do not hesitate to send us your inquiry and we will be happy to serve you..
        /// </summary>
        public static string HappyToHelp {
            get {
                return ResourceManager.GetString("HappyToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you suffer from any health impairment?.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Structure.
        /// </summary>
        public static string HQ {
            get {
                return ResourceManager.GetString("HQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity No..
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor Relations.
        /// </summary>
        public static string InvestorRelations {
            get {
                return ResourceManager.GetString("InvestorRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment application.
        /// </summary>
        public static string JobApp {
            get {
                return ResourceManager.GetString("JobApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Application.
        /// </summary>
        public static string JobApplication {
            get {
                return ResourceManager.GetString("JobApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job description.
        /// </summary>
        public static string JobDes {
            get {
                return ResourceManager.GetString("JobDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact the Recruitment Department.
        /// </summary>
        public static string JobsContact {
            get {
                return ResourceManager.GetString("JobsContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kingdom of Saudi Arabia.
        /// </summary>
        public static string KSA {
            get {
                return ResourceManager.GetString("KSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Skills.
        /// </summary>
        public static string LanguageSkills {
            get {
                return ResourceManager.GetString("LanguageSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for leaving.
        /// </summary>
        public static string LeaveReaseon {
            get {
                return ResourceManager.GetString("LeaveReaseon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like us on Facebook.
        /// </summary>
        public static string LikeUsOnFace {
            get {
                return ResourceManager.GetString("LikeUsOnFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our location on the map.
        /// </summary>
        public static string LocationMap {
            get {
                return ResourceManager.GetString("LocationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string MediaAndVideos {
            get {
                return ResourceManager.GetString("MediaAndVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Center.
        /// </summary>
        public static string MediaCenter {
            get {
                return ResourceManager.GetString("MediaCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Relations.
        /// </summary>
        public static string MediaContact {
            get {
                return ResourceManager.GetString("MediaContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;مرحبا بكم في النشرة الإخبارية للوطنية للصناعة &lt;/p&gt;
        ///&lt;p&gt;يسعدنا ان نقدم لكم في هذه النسخة أخر الأخبار. نأمل أن تجد هذه النشرة أهتمامكم.&lt;/p&gt;
        ///
        ///&lt;h3&gt;{0}&lt;/h3&gt;
        ///&lt;p&gt;للاطلاع على الخبر النقر على الرابط التالي&lt;/p&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string NewsBodyAr {
            get {
                return ResourceManager.GetString("NewsBodyAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Welcome to Al Watania for Industries Newsletter&lt;/p&gt;
        ///
        ///&lt;p&gt;We are pleased share with you in this edition the latest news, we hope you find it interesting&lt;/p&gt;
        ///
        ///&lt;h3&gt;{0}&lt;/h3&gt;
        ///&lt;p&gt;To read the full story please click on the following link &lt;/p&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string NewsBodyEn {
            get {
                return ResourceManager.GetString("NewsBodyEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in news.
        /// </summary>
        public static string NewsSearch {
            get {
                return ResourceManager.GetString("NewsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Saudi Nationality.
        /// </summary>
        public static string NonSaudiNationality {
            get {
                return ResourceManager.GetString("NonSaudiNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alwatania on Facebook.
        /// </summary>
        public static string OnFacebook {
            get {
                return ResourceManager.GetString("OnFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alwatania on Twitter.
        /// </summary>
        public static string OnTwitter {
            get {
                return ResourceManager.GetString("OnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication.
        /// </summary>
        public static string OpendedReports {
            get {
                return ResourceManager.GetString("OpendedReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other language.
        /// </summary>
        public static string OtherLanguage {
            get {
                return ResourceManager.GetString("OtherLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other questions.
        /// </summary>
        public static string OtherQuestions {
            get {
                return ResourceManager.GetString("OtherQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Factories.
        /// </summary>
        public static string OurFactories {
            get {
                return ResourceManager.GetString("OurFactories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string OurMessage {
            get {
                return ResourceManager.GetString("OurMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place &amp; Date.
        /// </summary>
        public static string PlaceAndDate {
            get {
                return ResourceManager.GetString("PlaceAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of issue.
        /// </summary>
        public static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to unit&apos;s procusts page.
        /// </summary>
        public static string PleaseGoToProcustsPage {
            get {
                return ResourceManager.GetString("PleaseGoToProcustsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Birth.
        /// </summary>
        public static string POB {
            get {
                return ResourceManager.GetString("POB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies and Governance.
        /// </summary>
        public static string PoliciesandGovernance {
            get {
                return ResourceManager.GetString("PoliciesandGovernance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product .
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in products.
        /// </summary>
        public static string ProductSearch {
            get {
                return ResourceManager.GetString("ProductSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Center.
        /// </summary>
        public static string PublicationCenter {
            get {
                return ResourceManager.GetString("PublicationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read also.
        /// </summary>
        public static string ReadAlso {
            get {
                return ResourceManager.GetString("ReadAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People can refer to them.
        /// </summary>
        public static string RefPersons {
            get {
                return ResourceManager.GetString("RefPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative relation.
        /// </summary>
        public static string RelativeRelation {
            get {
                return ResourceManager.GetString("RelativeRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a relative working in a company of national industries ?.
        /// </summary>
        public static string RelativeWorker {
            get {
                return ResourceManager.GetString("RelativeWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هدفنا المصداقية المتبادلة مع الجمهور حيث يتم عرض التقرير السنوي لمجموعة شركات الوطنية في هذه الصفحة حيثت يتم عرض التقارير السنوية والأرباح الربع سنوية حسب كل شركة.
        /// </summary>
        public static string ReportSummary {
            get {
                return ResourceManager.GetString("ReportSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string RequestedImage {
            get {
                return ResourceManager.GetString("RequestedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested quantity.
        /// </summary>
        public static string RequestedQuantity {
            get {
                return ResourceManager.GetString("RequestedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved © Alwatania For Industries {0}.
        /// </summary>
        public static string RightsReserved {
            get {
                return ResourceManager.GetString("RightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riyadh.
        /// </summary>
        public static string Riyadh {
            get {
                return ResourceManager.GetString("Riyadh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date H.
        /// </summary>
        public static string RleaseDateH {
            get {
                return ResourceManager.GetString("RleaseDateH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi.
        /// </summary>
        public static string SaudiNationality {
            get {
                return ResourceManager.GetString("SaudiNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in.
        /// </summary>
        public static string SearchIn {
            get {
                return ResourceManager.GetString("SearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in activities.
        /// </summary>
        public static string SearchInActivities {
            get {
                return ResourceManager.GetString("SearchInActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second academic qualification.
        /// </summary>
        public static string SecondAcademic {
            get {
                return ResourceManager.GetString("SecondAcademic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Industrial City.
        /// </summary>
        public static string SecondIndustry {
            get {
                return ResourceManager.GetString("SecondIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send application.
        /// </summary>
        public static string SendApp {
            get {
                return ResourceManager.GetString("SendApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send comment.
        /// </summary>
        public static string SendComent {
            get {
                return ResourceManager.GetString("SendComent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share activity.
        /// </summary>
        public static string ShareActivity {
            get {
                return ResourceManager.GetString("ShareActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the article.
        /// </summary>
        public static string ShareArticle {
            get {
                return ResourceManager.GetString("ShareArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share product.
        /// </summary>
        public static string ShareProduct {
            get {
                return ResourceManager.GetString("ShareProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Programms.
        /// </summary>
        public static string SocialPrograms {
            get {
                return ResourceManager.GetString("SocialPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Responsibility.
        /// </summary>
        public static string SocialResponsibility {
            get {
                return ResourceManager.GetString("SocialResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social status.
        /// </summary>
        public static string SocialStatus {
            get {
                return ResourceManager.GetString("SocialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board of Directors.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When can you start working?.
        /// </summary>
        public static string StartWorking {
            get {
                return ResourceManager.GetString("StartWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit comment.
        /// </summary>
        public static string SubmitComment {
            get {
                return ResourceManager.GetString("SubmitComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the order.
        /// </summary>
        public static string SubmitOrder {
            get {
                return ResourceManager.GetString("SubmitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit request.
        /// </summary>
        public static string SubmitRequest {
            get {
                return ResourceManager.GetString("SubmitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe in our Newsletters.
        /// </summary>
        public static string Subscripe {
            get {
                return ResourceManager.GetString("Subscripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development and training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategic Business Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        public static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Values.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View report.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision, Mission and Values.
        /// </summary>
        public static string VisionAndMessage {
            get {
                return ResourceManager.GetString("VisionAndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widowed.
        /// </summary>
        public static string Widowed {
            get {
                return ResourceManager.GetString("Widowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll contact you.
        /// </summary>
        public static string WillContact {
            get {
                return ResourceManager.GetString("WillContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows OS.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
